SET search_path TO tap, public;
SELECT plan(18);
SELECT has_table(:'schema', 'fare_attributes', 'table fare_attributes exists');
SELECT has_pk(:'schema', 'fare_attributes', 'table fare_attributes has primary key');
SELECT has_column(:'schema', 'fare_attributes', 'feed_index', 'table fare_attributes has column feed_index');
SELECT col_type_is(:'schema', 'fare_attributes', 'feed_index', 'integer', 'column fare_attributes.feed_index is integer');
SELECT has_column(:'schema', 'fare_attributes', 'fare_id', 'table fare_attributes has column fare_id');
SELECT col_type_is(:'schema', 'fare_attributes', 'fare_id', 'text', 'column fare_attributes.fare_id is text');
SELECT has_column(:'schema', 'fare_attributes', 'price', 'table fare_attributes has column price');
SELECT col_type_is(:'schema', 'fare_attributes', 'price', 'double precision', 'column fare_attributes.price is double precision');
SELECT has_column(:'schema', 'fare_attributes', 'currency_type', 'table fare_attributes has column currency_type');
SELECT col_type_is(:'schema', 'fare_attributes', 'currency_type', 'text', 'column fare_attributes.currency_type is text');
SELECT has_column(:'schema', 'fare_attributes', 'payment_method', 'table fare_attributes has column payment_method');
SELECT col_type_is(:'schema', 'fare_attributes', 'payment_method', 'integer', 'column fare_attributes.payment_method is integer');
SELECT has_column(:'schema', 'fare_attributes', 'transfers', 'table fare_attributes has column transfers');
SELECT col_type_is(:'schema', 'fare_attributes', 'transfers', 'integer', 'column fare_attributes.transfers is integer');
SELECT has_column(:'schema', 'fare_attributes', 'transfer_duration', 'table fare_attributes has column transfer_duration');
SELECT col_type_is(:'schema', 'fare_attributes', 'transfer_duration', 'integer', 'column fare_attributes.transfer_duration is integer');
SELECT has_column(:'schema', 'fare_attributes', 'agency_id', 'table fare_attributes has column agency_id');
SELECT col_type_is(:'schema', 'fare_attributes', 'agency_id', 'text', 'column fare_attributes.agency_id is text');
SELECT * FROM finish();
