SET search_path TO tap, public;
SELECT plan(33);
SELECT has_table(:'schema', 'trips', 'table trips exists');
SELECT has_pk(:'schema', 'trips', 'table trips has primary key');
SELECT is_indexed(:'schema', 'trips', ARRAY['feed_index', 'service_id']);
SELECT has_column(:'schema', 'trips', 'feed_index', 'table trips has column feed_index');
SELECT col_type_is(:'schema', 'trips', 'feed_index', 'integer', 'column trips.feed_index is integer');
SELECT has_column(:'schema', 'trips', 'route_id', 'table trips has column route_id');
SELECT col_type_is(:'schema', 'trips', 'route_id', 'text', 'column trips.route_id is text');
SELECT has_column(:'schema', 'trips', 'service_id', 'table trips has column service_id');
SELECT col_type_is(:'schema', 'trips', 'service_id', 'text', 'column trips.service_id is text');
SELECT has_column(:'schema', 'trips', 'trip_id', 'table trips has column trip_id');
SELECT col_type_is(:'schema', 'trips', 'trip_id', 'text', 'column trips.trip_id is text');
SELECT has_column(:'schema', 'trips', 'trip_headsign', 'table trips has column trip_headsign');
SELECT col_type_is(:'schema', 'trips', 'trip_headsign', 'text', 'column trips.trip_headsign is text');
SELECT has_column(:'schema', 'trips', 'direction_id', 'table trips has column direction_id');
SELECT col_type_is(:'schema', 'trips', 'direction_id', 'integer', 'column trips.direction_id is integer');
SELECT has_column(:'schema', 'trips', 'block_id', 'table trips has column block_id');
SELECT col_type_is(:'schema', 'trips', 'block_id', 'text', 'column trips.block_id is text');
SELECT has_column(:'schema', 'trips', 'shape_id', 'table trips has column shape_id');
SELECT col_type_is(:'schema', 'trips', 'shape_id', 'text', 'column trips.shape_id is text');
SELECT has_column(:'schema', 'trips', 'trip_short_name', 'table trips has column trip_short_name');
SELECT col_type_is(:'schema', 'trips', 'trip_short_name', 'text', 'column trips.trip_short_name is text');
SELECT has_column(:'schema', 'trips', 'wheelchair_accessible', 'table trips has column wheelchair_accessible');
SELECT col_type_is(:'schema', 'trips', 'wheelchair_accessible', 'integer', 'column trips.wheelchair_accessible is integer');
SELECT has_column(:'schema', 'trips', 'direction', 'table trips has column direction');
SELECT col_type_is(:'schema', 'trips', 'direction', 'text', 'column trips.direction is text');
SELECT has_column(:'schema', 'trips', 'schd_trip_id', 'table trips has column schd_trip_id');
SELECT col_type_is(:'schema', 'trips', 'schd_trip_id', 'text', 'column trips.schd_trip_id is text');
SELECT has_column(:'schema', 'trips', 'trip_type', 'table trips has column trip_type');
SELECT col_type_is(:'schema', 'trips', 'trip_type', 'text', 'column trips.trip_type is text');
SELECT has_column(:'schema', 'trips', 'exceptional', 'table trips has column exceptional');
SELECT col_type_is(:'schema', 'trips', 'exceptional', 'integer', 'column trips.exceptional is integer');
SELECT has_column(:'schema', 'trips', 'bikes_allowed', 'table trips has column bikes_allowed');
SELECT col_type_is(:'schema', 'trips', 'bikes_allowed', 'integer', 'column trips.bikes_allowed is integer');
SELECT * FROM finish();
