SET search_path TO tap, public;
SELECT plan(18);
SELECT has_table(:'schema', 'frequencies', 'table frequencies exists');
SELECT has_pk(:'schema', 'frequencies', 'table frequencies has primary key');
SELECT has_column(:'schema', 'frequencies', 'feed_index', 'table frequencies has column feed_index');
SELECT col_type_is(:'schema', 'frequencies', 'feed_index', 'integer', 'column frequencies.feed_index is integer');
SELECT has_column(:'schema', 'frequencies', 'trip_id', 'table frequencies has column trip_id');
SELECT col_type_is(:'schema', 'frequencies', 'trip_id', 'text', 'column frequencies.trip_id is text');
SELECT has_column(:'schema', 'frequencies', 'start_time', 'table frequencies has column start_time');
SELECT col_type_is(:'schema', 'frequencies', 'start_time', 'text', 'column frequencies.start_time is text');
SELECT has_column(:'schema', 'frequencies', 'end_time', 'table frequencies has column end_time');
SELECT col_type_is(:'schema', 'frequencies', 'end_time', 'text', 'column frequencies.end_time is text');
SELECT has_column(:'schema', 'frequencies', 'headway_secs', 'table frequencies has column headway_secs');
SELECT col_type_is(:'schema', 'frequencies', 'headway_secs', 'integer', 'column frequencies.headway_secs is integer');
SELECT has_column(:'schema', 'frequencies', 'exact_times', 'table frequencies has column exact_times');
SELECT col_type_is(:'schema', 'frequencies', 'exact_times', 'integer', 'column frequencies.exact_times is integer');
SELECT has_column(:'schema', 'frequencies', 'start_time_seconds', 'table frequencies has column start_time_seconds');
SELECT col_type_is(:'schema', 'frequencies', 'start_time_seconds', 'integer', 'column frequencies.start_time_seconds is integer');
SELECT has_column(:'schema', 'frequencies', 'end_time_seconds', 'table frequencies has column end_time_seconds');
SELECT col_type_is(:'schema', 'frequencies', 'end_time_seconds', 'integer', 'column frequencies.end_time_seconds is integer');
SELECT * FROM finish();
