SET search_path TO tap, public;
SELECT plan(35);
SELECT has_table(:'schema', 'stop_times', 'table stop_times exists');
SELECT has_pk(:'schema', 'stop_times', 'table stop_times has primary key');
SELECT is_indexed(:'schema', 'stop_times', ARRAY['feed_index', 'trip_id', 'stop_id']);
SELECT is_indexed(:'schema', 'stop_times', ARRAY['arrival_time_seconds']);
SELECT is_indexed(:'schema', 'stop_times', ARRAY['departure_time_seconds']);
SELECT has_column(:'schema', 'stop_times', 'feed_index', 'table stop_times has column feed_index');
SELECT col_type_is(:'schema', 'stop_times', 'feed_index', 'integer', 'column stop_times.feed_index is integer');
SELECT has_column(:'schema', 'stop_times', 'trip_id', 'table stop_times has column trip_id');
SELECT col_type_is(:'schema', 'stop_times', 'trip_id', 'text', 'column stop_times.trip_id is text');
SELECT has_column(:'schema', 'stop_times', 'arrival_time', 'table stop_times has column arrival_time');
SELECT col_type_is(:'schema', 'stop_times', 'arrival_time', 'interval', 'column stop_times.arrival_time is interval');
SELECT has_column(:'schema', 'stop_times', 'departure_time', 'table stop_times has column departure_time');
SELECT col_type_is(:'schema', 'stop_times', 'departure_time', 'interval', 'column stop_times.departure_time is interval');
SELECT has_column(:'schema', 'stop_times', 'stop_id', 'table stop_times has column stop_id');
SELECT col_type_is(:'schema', 'stop_times', 'stop_id', 'text', 'column stop_times.stop_id is text');
SELECT has_column(:'schema', 'stop_times', 'stop_sequence', 'table stop_times has column stop_sequence');
SELECT col_type_is(:'schema', 'stop_times', 'stop_sequence', 'integer', 'column stop_times.stop_sequence is integer');
SELECT has_column(:'schema', 'stop_times', 'stop_headsign', 'table stop_times has column stop_headsign');
SELECT col_type_is(:'schema', 'stop_times', 'stop_headsign', 'text', 'column stop_times.stop_headsign is text');
SELECT has_column(:'schema', 'stop_times', 'pickup_type', 'table stop_times has column pickup_type');
SELECT col_type_is(:'schema', 'stop_times', 'pickup_type', 'integer', 'column stop_times.pickup_type is integer');
SELECT has_column(:'schema', 'stop_times', 'drop_off_type', 'table stop_times has column drop_off_type');
SELECT col_type_is(:'schema', 'stop_times', 'drop_off_type', 'integer', 'column stop_times.drop_off_type is integer');
SELECT has_column(:'schema', 'stop_times', 'shape_dist_traveled', 'table stop_times has column shape_dist_traveled');
SELECT col_type_is(:'schema', 'stop_times', 'shape_dist_traveled', 'numeric(10,2)', 'column stop_times.shape_dist_traveled is numeric(10,2)');
SELECT has_column(:'schema', 'stop_times', 'timepoint', 'table stop_times has column timepoint');
SELECT col_type_is(:'schema', 'stop_times', 'timepoint', 'integer', 'column stop_times.timepoint is integer');
SELECT has_column(:'schema', 'stop_times', 'continuous_drop_off', 'table stop_times has column continuous_drop_off');
SELECT col_type_is(:'schema', 'stop_times', 'continuous_drop_off', 'integer', 'column stop_times.continuous_drop_off is integer');
SELECT has_column(:'schema', 'stop_times', 'continuous_pickup', 'table stop_times has column continuous_pickup');
SELECT col_type_is(:'schema', 'stop_times', 'continuous_pickup', 'integer', 'column stop_times.continuous_pickup is integer');
SELECT has_column(:'schema', 'stop_times', 'arrival_time_seconds', 'table stop_times has column arrival_time_seconds');
SELECT col_type_is(:'schema', 'stop_times', 'arrival_time_seconds', 'integer', 'column stop_times.arrival_time_seconds is integer');
SELECT has_column(:'schema', 'stop_times', 'departure_time_seconds', 'table stop_times has column departure_time_seconds');
SELECT col_type_is(:'schema', 'stop_times', 'departure_time_seconds', 'integer', 'column stop_times.departure_time_seconds is integer');
SELECT * FROM finish();
