SET search_path TO tap, public;
SELECT plan(16);
SELECT has_table(:'schema', 'fare_rules', 'table fare_rules exists');
SELECT has_pk(:'schema', 'fare_rules', 'table fare_rules has primary key');
SELECT has_column(:'schema', 'fare_rules', 'feed_index', 'table fare_rules has column feed_index');
SELECT col_type_is(:'schema', 'fare_rules', 'feed_index', 'integer', 'column fare_rules.feed_index is integer');
SELECT has_column(:'schema', 'fare_rules', 'fare_id', 'table fare_rules has column fare_id');
SELECT col_type_is(:'schema', 'fare_rules', 'fare_id', 'text', 'column fare_rules.fare_id is text');
SELECT has_column(:'schema', 'fare_rules', 'route_id', 'table fare_rules has column route_id');
SELECT col_type_is(:'schema', 'fare_rules', 'route_id', 'text', 'column fare_rules.route_id is text');
SELECT has_column(:'schema', 'fare_rules', 'origin_id', 'table fare_rules has column origin_id');
SELECT col_type_is(:'schema', 'fare_rules', 'origin_id', 'text', 'column fare_rules.origin_id is text');
SELECT has_column(:'schema', 'fare_rules', 'destination_id', 'table fare_rules has column destination_id');
SELECT col_type_is(:'schema', 'fare_rules', 'destination_id', 'text', 'column fare_rules.destination_id is text');
SELECT has_column(:'schema', 'fare_rules', 'contains_id', 'table fare_rules has column contains_id');
SELECT col_type_is(:'schema', 'fare_rules', 'contains_id', 'text', 'column fare_rules.contains_id is text');
SELECT has_column(:'schema', 'fare_rules', 'service_id', 'table fare_rules has column service_id');
SELECT col_type_is(:'schema', 'fare_rules', 'service_id', 'text', 'column fare_rules.service_id is text');
SELECT * FROM finish();
