SET search_path TO tap, public;
SELECT plan(22);
SELECT has_table(:'schema', 'agency', 'table agency exists');
SELECT has_pk(:'schema', 'agency', 'table agency has primary key');
SELECT has_column(:'schema', 'agency', 'feed_index', 'table agency has column feed_index');
SELECT col_type_is(:'schema', 'agency', 'feed_index', 'integer', 'column agency.feed_index is integer');
SELECT has_column(:'schema', 'agency', 'agency_id', 'table agency has column agency_id');
SELECT col_type_is(:'schema', 'agency', 'agency_id', 'text', 'column agency.agency_id is text');
SELECT has_column(:'schema', 'agency', 'agency_name', 'table agency has column agency_name');
SELECT col_type_is(:'schema', 'agency', 'agency_name', 'text', 'column agency.agency_name is text');
SELECT has_column(:'schema', 'agency', 'agency_url', 'table agency has column agency_url');
SELECT col_type_is(:'schema', 'agency', 'agency_url', 'text', 'column agency.agency_url is text');
SELECT has_column(:'schema', 'agency', 'agency_timezone', 'table agency has column agency_timezone');
SELECT col_type_is(:'schema', 'agency', 'agency_timezone', 'text', 'column agency.agency_timezone is text');
SELECT has_column(:'schema', 'agency', 'agency_lang', 'table agency has column agency_lang');
SELECT col_type_is(:'schema', 'agency', 'agency_lang', 'text', 'column agency.agency_lang is text');
SELECT has_column(:'schema', 'agency', 'agency_phone', 'table agency has column agency_phone');
SELECT col_type_is(:'schema', 'agency', 'agency_phone', 'text', 'column agency.agency_phone is text');
SELECT has_column(:'schema', 'agency', 'agency_fare_url', 'table agency has column agency_fare_url');
SELECT col_type_is(:'schema', 'agency', 'agency_fare_url', 'text', 'column agency.agency_fare_url is text');
SELECT has_column(:'schema', 'agency', 'agency_email', 'table agency has column agency_email');
SELECT col_type_is(:'schema', 'agency', 'agency_email', 'text', 'column agency.agency_email is text');
SELECT has_column(:'schema', 'agency', 'bikes_policy_url', 'table agency has column bikes_policy_url');
SELECT col_type_is(:'schema', 'agency', 'bikes_policy_url', 'text', 'column agency.bikes_policy_url is text');
SELECT * FROM finish();
